M48
; DRILL file {KiCad (7.0.0)} date Wed Jun 28 18:16:22 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-28T18:16:22+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
%
G90
G05
T1
X6.1822Y-4.6215
T1
G00X6.4135Y-4.6215
M15
G01X6.4233Y-4.6215
M16
G05
T0
M30
